names_set = set()
names_set.update(["nilanshu","anshul","sam","yash","diya","khushi","selvi"])
print("set after adding names:",names_set)
names_set.discard("yash")
names_set.add("Abhiraj")
print("set after modifying a name:",names_set)
names_set.discard("abhiraj")
names_set.discard("nilanshu")
print("set after deleting two names:",names_set)
